
// ajax action types
export const REQUEST_GRID_DOCUMENT_LOAD = 'REQUEST-GRID_DOCUMENT-LOAD';
export const REQUEST_GRID_DOCUMENT_CHECK_DRAFT_STATE = 'REQUEST-GRID_DOCUMENT-CHECK_DRAFT_STATE'
export const REQUEST_GRID_DOCUMENT_PUBLISH_DRAFT = 'REQUEST-GRID_DOCUMENT-PUBLISH_DRAFT';
export const REQUEST_GRID_DOCUMENT_REVERT_DRAFT = 'REQUEST-GRID_DOCUMENT-REVERT_DRAFT';
export const REQUEST_GRID_DOCUMENT_REVERT_TO_REVISION = 'REQUEST-GRID_DOCUMENT-REVERT_TO_REVISION';
export const REQUEST_GRID_DOCUMENT_REVISIONS = 'REQUEST-GRID_DOCUMENT-REVISIONS';
export const REQUEST_GRID_STYLES_GET = 'REQUEST-GRID_STYLES-GET';
export const REQUEST_GRID_PERMISSION_RIGHTS = 'REQUEST-GRID_PERMISSION-RIGHTS';

export const REQUEST_GRID_CONTAINER_EDITING_GET_TYPES = 'REQUEST-GRID_CONTAINER_EDITING-GET_TYPES';
export const REQUEST_GRID_CONTAINER_EDITING_ADD = 'REQUEST-GRID_CONTAINER_EDITING-ADD';
export const REQUEST_GRID_CONTAINER_EDITING_DELETE = 'REQUEST-GRID_CONTAINER_EDITING-DELETE';
export const REQUEST_GRID_CONTAINER_EDITING_MOVE = 'REQUEST-GRID_CONTAINER_EDITING-MOVE';

export const REQUEST_GRID_BOX_EDITING_META_TYPES = 'REQUEST-GRID_BOX_EDITING-META_TYPES';
export const REQUEST_GRID_BOX_EDITING_SEARCH = 'REQUEST-GRID_BOX_EDITING-SEARCH';
export const REQUEST_GRID_BOX_EDITING_CREATE = 'REQUEST-GRID_BOX_EDITING-CREATE';
export const REQUEST_GRID_BOX_EDITING_MOVE = 'REQUEST-GRID_BOX_EDITING-MOVE';
export const REQUEST_GRID_BOX_EDITING_REMOVE = 'REQUEST-GRID_BOX_EDITING-REMOVE';
export const REQUEST_GRID_BOX_EDITING_UPDATE = 'REQUEST-GRID_BOX_EDITING-UPDATE';



export const GRID_LOADING = 'GRID_LOADING';

export const GRID_CONTAINER_EDIT = "GRID-CONTAINER-EDIT";
export const GRID_BOX_EDIT = "GRID-BOX-EDIT";

