module.exports = [
	{
		"type":"i-0",
		"space_to_left":null,
		"space_to_right":null,
		"numslots":"0"
	},
	{
		"type":"c-1d3-1d3-1d3",
		"space_to_left":null,
		"space_to_right":null,
		"numslots":"3"
	},
	{
		"type":"c-2d3-1d3",
		"space_to_left":null,
		"space_to_right":null,
		"numslots":"2"
	},
	{
		"type":"c-1d3-2d3",
		"space_to_left":null,
		"space_to_right":null,
		"numslots":"2"
	},
	{
		"type":"c-1d6-1d6-1d6-1d6-1d6-1d6",
		"space_to_left":null,
		"space_to_right":null,
		"numslots":"6"
	},
	{
		"type":"c-1d4-1d4-1d4-1d4",
		"space_to_left":null,
		"space_to_right":null,
		"numslots":"4"
	},
	{
		"type":"c-1d2-1d2",
		"space_to_left":null,
		"space_to_right":null,
		"numslots":"2"
	},
	{
		"type":"s-1d3-0",
		"space_to_left":null,
		"space_to_right":"2d3",
		"numslots":"1"
	},
	{
		"type":"s-0-1d3",
		"space_to_left":"2d3",
		"space_to_right":null,
		"numslots":"1"
	},
	{
		"type":"sc-1d3",
		"space_to_left":null,
		"space_to_right":null,
		"numslots":"1"
	},
	{
		"type":"c-0-1d3-1d3",
		"space_to_left":"1d3",
		"space_to_right":null,
		"numslots":"2"
	},
	{
		"type":"c-1d3-1d3-0",
		"space_to_left":null,
		"space_to_right":"1d3",
		"numslots":"2"
	},
	{
		"type":"c-0-2d3",
		"space_to_left":"1d3",
		"space_to_right":null,
		"numslots":"1"
	},
	{
		"type":"c-2d3-0",
		"space_to_left":null,
		"space_to_right":"1d3",
		"numslots":"1"
	}
];